name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
         docker build . --file dockerfile --tag nginx-exclusive:latest
         docker run -d -p 80:80 nginx-exclusive
         docker inspect nginx-exclusive
